/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOrder: typeof import('./src/components/AddOrder.vue')['default']
    Address: typeof import('./src/components/Address.vue')['default']
    AddressEdit: typeof import('./src/components/AddressEdit.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NOWIFI: typeof import('./src/components/NOWIFI.vue')['default']
    Order: typeof import('./src/components/Order.vue')['default']
    PaySuccess: typeof import('./src/components/PaySuccess.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/User.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanList: typeof import('vant/es')['List']
    VanPopup: typeof import('vant/es')['Popup']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
