spring:
    application:
        name: reggie-takeout
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/reggie
        username: postgres
        password: 18054566672

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true  # 在映射实体或者属性时, 将数据库中表名和字段名中的下划线去掉, 开启按照驼峰命名法映射
        log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    global-config:
        db-config:
            id-type: ASSIGN_ID
logging:
    level:
        root: info
reggie:
    path: D:\images\
